name: ArtBlocks

on:
  schedule:
    - cron: "30 0/6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: db

      - name: Install Dependencies
        run: |
          yarn

      - name: Run script
        run: |
          yarn script scripts/artblocks.ts
        env:
          OPEN_SEA_API_KEY: ${{secrets.OPEN_SEA_API_KEY}}

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitActionBot
          message: Update ArtBlocks
          branch: db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
