name: Hashmasks

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: db

      - name: Install Dependencies
        run: |
          yarn

      - name: Run script
        run: |
          yarn script scripts/hashmasks.ts

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitActionBot
          message: Update Hashmasks
          branch: db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
