name: CryptoPunks

on:
  schedule:
    - cron: "0 9/12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: db

      - name: Install Dependencies
        run: |
          yarn

      - name: Run script
        run: |
          yarn script scripts/punks.ts

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitActionBot
          message: Update CryptoPunks
          branch: db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_ENDPOINT: ${{secrets.DATABASE_ENDPOINT}}
          INFURA_ID: ${{secrets.INFURA_ID}}
