name: Spacebudz

on:
  schedule:
    - cron: "0 5/6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: db

      - name: Install Dependencies
        run: |
          yarn

      - name: Run script
        run: |
          yarn script scripts/spacebudz.ts

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitActionBot
          message: Update Spacebudz
          branch: db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
